### ISSUE TITLE
Interface type definitions return broken types

### ISSUE THREAD

**Issue by stevelizcano** [gzuidhof/tygo#13]
If I define an interface with methods, the type returned is broken. For example:

```
type DeploymentService interface {

  CreateDeployment(ctx context.Context, input CreateDeploymentInput)
  ....
}
```

Will return the following ill-formatted type such as:

```
export type DeploymentService = 
;
```

Which shows as an error in TS.

Ideally, it should return an empty type or no type at all (skip processing, I believe). 

Otherwise, fantastic library and it's a big help.

**Comment by gzuidhof** [comment]
Definitely a bug - happy to accept contributions that fix this.
For now I imagine you can work around it by ignoring files that contain these types of interfaces.. Not the nicest solution, but it should work. Once #11 lands there should be another workaround that is more precise.

**Comment by stevelizcano** [comment]
Thanks. If you can point me where to look to start testing, I can happily start from there.

**Comment by ManoloTonto1** [comment]
> Thanks. If you can point me where to look to start testing, I can happily start from there.

I think you can find it if you fork it and find somewhere where it mentions `interface`  in the AST. 
I will be happy to contribute to this if @stevelizcano doesn't end up making a pr.

**Comment by jabalsad** [comment]
I'm having problem generating types like these:

```go
type MyType map[string]any
```

Which just results in a broken typescript type. I've tried using type mappings as follows, but it doesn't work:

```
				TypeMappings: map[string]string{
					"interface{}":        "unknown",
				},
```

**Comment by gzuidhof** [comment]
It's been a while - but I can confirm the first issue, interfaces should not have an output. Should be fixed with https://github.com/gzuidhof/tygo/pull/32 


----


@jabalsad I wasn't able to reproduce your example:

```golang
type MyType map[string]any
```
outputs
```ts
export type MyType = { [key: string]: any};
```

Do you maybe have a snippet where it breaks?
