### ISSUE TITLE
Generate fields for types that are composed of subtypes

### ISSUE THREAD

**Issue by petterhs** [gzuidhof/tygo#15]
Hi! Thank you for your generator!

I'm trying to generate types where I have a type that is composed of subtypes. Is there something I can do in order for this to work.

Example:
```
type Base struct {
    Name   string  `json:"name"`
}

type Other struct {
    Base
    OtherField  string `json:"otherField"`
}
```

Expected output:
```
export interface Other {
  name: string;
  otherField: string;
}
```

**Comment by gzuidhof** [comment]
Will close this now that #30 landed in release `0.2.7`
