### ISSUE TITLE
Directive comments on type/const statements break generation

### ISSUE THREAD

**Issue by assafvayner** [gzuidhof/tygo#26]
## Description:

Attempting to generate TS on type/const statements with go directives (or comments that match the directive regex) e.g. `type X int //revive:disable-line:exported` can cause improper TS code to be generated. The generated TS ends up including a `//` at the beginning of a comment without any text and no newline, such that if the next generated code is a block comment, its `/**` prefix is commented out causing broken code. (See example below for more clarity).

## Analysis:

I've traced the issue to [writing the comments on **type**](https://github.com/gzuidhof/tygo/blob/main/tygo/write_toplevel.go#L110) (and likewise [line 182](https://github.com/gzuidhof/tygo/blob/main/tygo/write_toplevel.go#L182)). When the comment is a directive,`{spec}.Comment.Text()` is an empty string, there is no newline being added at the end of the comment which would usually be there. So when the next generated code is a block comment it begins on the same line as a single line comment.

One suggestion to fix this would be to check that `{spec}.Comment.Text()` is not empty on top of `{spec}.Comment != nil`. This would then not even add an empty `//` if there is a directive. Would you be able to make this change? Or accept a PR to make this fix?

## Example:

`indexer.go`
```go
package indexer

const SomeValue = 3 //comment:test

// RepoIndexerType specifies the repository indexer type
type RepoIndexerType int //revive:disable-line:exported

const (
	// RepoIndexerTypeCode code indexer
	RepoIndexerTypeCode RepoIndexerType = iota // 0
	// RepoIndexerTypeStats repository stats indexer
	RepoIndexerTypeStats // 1
)
```

Generated `index.ts`, note the occurrences of `// /**` which breaks the block comments
```typescript
// Code generated by tygo. DO NOT EDIT.

//////////
// source: indexer.go

export const SomeValue = 3; // /**
 * RepoIndexerType specifies the repository indexer type
 */
export type RepoIndexerType = number /* int */; // /**
 * RepoIndexerTypeCode code indexer
 */
export const RepoIndexerTypeCode: RepoIndexerType = 0; // 0
/**
 * RepoIndexerTypeStats repository stats indexer
 */
export const RepoIndexerTypeStats: RepoIndexerType = 1; // 1

```

`tygo.yaml`
```yaml
packages:
  - path: "indexer"
```

**Comment by gzuidhof** [comment]
Thank you for the detailed issue, that made it a breeze to pinpoint and fix :) 

See #33
