### ISSUE TITLE
Pointer types always translated as optional variables

### ISSUE THREAD

**Issue by mlafeldt** [gzuidhof/tygo#3]
I noticed that pointers are always translated to TS using `?`.

For example:

```go
type FollowerEvent struct {
	Follower            *twitter.User `json:"follower"`
}
```

Becomes:

```ts
export interface FollowerEvent {
  follower?: any /* twitter.User */;
}
```

While it's true that pointers are often used to express optional values, they're also used for e.g. efficiency reasons and the value might be "guaranteed" to be set.

Is there any way to remove the `?` for pointer types from the generated TS?

**Comment by gzuidhof** [comment]
There is no way to do this in the current version, but I don't see why it wouldn't make sense to support this.

Maybe we can add it like `omitempty` in the JSON struct tag? So something like

```golang
type FollowerEvent struct {
	Follower            *twitter.User `json:"follower" tstype:"nonoptional"`
        something            Something `json:"something" tstype:"MyCustomType,nonoptional"`
}
```

Or should it be a separate tag?

**Comment by gzuidhof** [comment]
Also I have considered at some point fleshing this entire project out more and adding directives in comments.. So you could comment

```
// @tygo non-optional
```
or something similar..

**Comment by mlafeldt** [comment]
Yes, something like `tstype:",nonoptional"` or `tstype:",required"` sounds good!

**Comment by gzuidhof** [comment]
That was pretty easy to implement :) Could you review #4 before I merge it?
