### ISSUE TITLE
Feature request `TSType()` Method returning the tstype

### ISSUE THREAD

**Issue by 9glenda** [gzuidhof/tygo#38]
Similar to the `String()` method.
```go
type MyType struct {
   custom CustomType // the struct tag `tstype:"'string1' | 'string2'" is not needed anymore
}
type CustomType struct {
  field1 string
  field2 string
}
func (c CustomType) TSType() string {
  return "'string1' | 'string2'"
}

**Comment by OGreeni** [comment]
I will open a PR to add this feature.

**Comment by gzuidhof** [comment]
As `tygo` does not actually execute the code, but instead statically analyzes/transpiles it, this would actually make things more difficult over using tags.

I would say tags are also less poluting to your code in general, so I'm not really convinced of the merit of having it in a function instead.
